import json
import math
import os
import re
import shutil
import time
from datasets import Dataset, load_dataset
from datasketch import MinHash, MinHashLSH
from huggingface_hub import HfApi, hf_hub_download, login
from tree_sitter_language_pack import get_parser

# ==========================================
# 1. AUTHENTICATION & HUB TARGET
# ==========================================
HF_TOKEN = os.environ.get("HF_TOKEN")
if not HF_TOKEN:
    raise ValueError("HF_TOKEN secret is missing in GitHub Environment!")

login(token=HF_TOKEN)

USER_NAME = "rufatronics"
DATASET_NAME = "clean-code-corpus-v1"
REPO_ID = f"{USER_NAME}/{DATASET_NAME}"
STATE_FILENAME = "pipeline_state.json"

STAGING_DIR = "./hf_staging"
os.makedirs(STAGING_DIR, exist_ok=True)

api = HfApi()
api.create_repo(
    repo_id=REPO_ID, repo_type="dataset", private=True, exist_ok=True
)
print(f"Target repository active: https://huggingface.co/datasets/{REPO_ID}")

# Safety limits: 5.25 hrs run max; flush commit every 45 mins (2700s)
MAX_RUNTIME_SECONDS = 5.25 * 3600
SYNC_INTERVAL_SECONDS = 45 * 60
START_TIME = time.time()
LAST_SYNC_TIME = time.time()

# ==========================================
# 2. REMOTE STATE & CONSOLIDATED SYNC
# ==========================================
def load_remote_state():
    try:
        state_path = hf_hub_download(
            repo_id=REPO_ID,
            filename=STATE_FILENAME,
            repo_type="dataset",
            token=HF_TOKEN,
        )
        with open(state_path, "r") as f:
            print("Loaded state from Hugging Face Hub.")
            return json.load(f)
    except Exception:
        print("No existing state found on Hub. Starting clean pipeline.")
        return {"completed_urls": [], "current_url": None, "last_index": 0}


def sync_staging_to_hf(state, commit_msg="Batch update shards and pipeline state"):
    global LAST_SYNC_TIME
    
    # Write current state directly inside staging directory to bundle in 1 commit
    state_file_path = os.path.join(STAGING_DIR, STATE_FILENAME)
    with open(state_file_path, "w") as f:
        json.dump(state, f, indent=2)

    files_to_push = os.listdir(STAGING_DIR)
    if not files_to_push:
        print("No files queued for upload.")
        return

    print(f"\n[SINGLE COMMIT] Syncing {len(files_to_push)} file(s) to HF Hub...")
    api.upload_folder(
        folder_path=STAGING_DIR,
        repo_id=REPO_ID,
        repo_type="dataset",
        commit_message=commit_msg,
    )
    print("Sync successful!")

    # Clear uploaded shards locally while keeping workspace clean
    shutil.rmtree(STAGING_DIR)
    os.makedirs(STAGING_DIR, exist_ok=True)
    LAST_SYNC_TIME = time.time()


state = load_remote_state()

# ==========================================
# 3. AST PARSER & SCRUBBING ENGINE
# ==========================================
LANGUAGE_MAP = {
    "python": "python",
    "c": "c",
    "cpp": "cpp",
    "javascript": "javascript",
    "go": "go",
    "rust": "rust",
    "java": "java",
    "typescript": "typescript",
}

PARSERS = {}
for lang, ts_lang in LANGUAGE_MAP.items():
    try:
        PARSERS[lang] = get_parser(ts_lang)
    except Exception:
        pass


def shannon_entropy(text: str) -> float:
    if not text:
        return 0.0
    prob = [float(text.count(c)) / len(text) for c in set(text)]
    return -sum(p * math.log2(p) for p in prob)


def passes_ruthless_scrubbing(example: dict) -> bool:
    code = example.get("code", "")
    raw_lang = (example.get("language") or "").lower().strip()

    if raw_lang == "c++":
        raw_lang = "cpp"

    if raw_lang not in LANGUAGE_MAP or raw_lang not in PARSERS:
        return False

    lines = code.splitlines()
    num_lines = len(lines)

    if num_lines < 30 or num_lines > 1200:
        return False

    avg_len = sum(len(l) for l in lines) / max(num_lines, 1)
    if avg_len < 18 or avg_len > 60:
        return False
    if max(len(l) for l in lines) > 180:
        return False

    total_chars = len(code)
    alpha_chars = sum(c.isalnum() for c in code)
    if (alpha_chars / max(total_chars, 1)) < 0.72:
        return False

    entropy = shannon_entropy(code)
    if entropy < 3.85 or entropy > 5.35:
        return False

    comment_lines = sum(
        1
        for l in lines
        if l.strip().startswith(("//", "#", "/*", "*", "'''", '"""'))
    )
    comment_ratio = comment_lines / float(num_lines)
    if comment_ratio < 0.05 or comment_ratio > 0.25:
        return False

    junk_patterns = [
        r"auto-generated",
        r"do not edit",
        r"swagger-codegen",
        r"pb\.go",
        r"unittest",
        r"pytest",
        r"licence_header",
        r"minified",
        r"generated by",
        r"mock",
        r"fixture",
        r"dist/",
        r"build/",
        r"testcase",
    ]
    code_sample = "\n".join(lines[:35]).lower()
    if any(re.search(p, code_sample) for p in junk_patterns):
        return False

    try:
        parser = PARSERS[raw_lang]
        tree = parser.parse(bytes(code, "utf8"))

        if tree.root_node.has_error:
            return False

        def get_max_depth(node):
            if not node.children:
                return 1
            return 1 + max(get_max_depth(child) for child in node.children)

        if get_max_depth(tree.root_node) < 8:
            return False
    except Exception:
        return False

    return True


# ==========================================
# 4. MINHASH DEDUPLICATION & BATCH ENGINE
# ==========================================
lsh = MinHashLSH(threshold=0.70, num_perm=128)


def get_minhash(code: str) -> MinHash:
    clean_code = re.sub(
        r"//.*|/\*[\s\S]*?\*/|#.*|\"\"\"[\s\S]*?\"\"\"|'''[\s\S]*?'''", "", code
    )
    tokens = clean_code.lower().split()
    m = MinHash(num_perm=128)
    for i in range(len(tokens) - 4):
        ngram = " ".join(tokens[i : i + 5])
        m.update(ngram.encode("utf-8"))
    return m


def is_unique(code: str, doc_id: str) -> bool:
    mh = get_minhash(code)
    result = lsh.query(mh)
    if result:
        return False
    lsh.insert(doc_id, mh)
    return True


TARGET_PATHS = [
    "hf://datasets/codeparrot/github-code-clean/data/Python/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/C/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/CPP/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/JavaScript/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/Go/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/Rust/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/Java/*.parquet",
    "hf://datasets/codeparrot/github-code-clean/data/TypeScript/*.parquet",
]

BATCH_SIZE = 10000  # Larger local shard size
cleaned_buffer = []
shard_counter = 0

for target_url in TARGET_PATHS:
    if target_url in state["completed_urls"]:
        print(f"Skipping completed URL pattern: {target_url}")
        continue

    print(f"\n--- Processing Target Pattern: {target_url} ---")

    dataset_stream = load_dataset(
        "parquet", data_files=target_url, streaming=True, split="train"
    )

    current_idx = 0
    resume_from = (
        state["last_index"] if state["current_url"] == target_url else 0
    )

    for item in dataset_stream:
        current_idx += 1

        if current_idx <= resume_from:
            continue

        now = time.time()
        # 1. Graceful Shutdown Check (Approaching GH Actions 6h limit)
        if (now - START_TIME) > MAX_RUNTIME_SECONDS:
            print("\nReaching GH Actions time limit! Staging remaining buffer and syncing...")
            if cleaned_buffer:
                shard_counter += 1
                shard = Dataset.from_list(cleaned_buffer)
                shard.to_parquet(f"{STAGING_DIR}/shard_{int(now)}_{shard_counter}.parquet")

            state["current_url"] = target_url
            state["last_index"] = current_idx
            sync_staging_to_hf(state, commit_msg="Automated timeout checkpoint")
            print("Job state synchronized safely. Exiting cleanly.")
            exit(0)

        # 2. Periodic HF Sync Check (Every 45 minutes)
        if (now - LAST_SYNC_TIME) > SYNC_INTERVAL_SECONDS:
            state["current_url"] = target_url
            state["last_index"] = current_idx
            sync_staging_to_hf(state, commit_msg="Periodic 45m checkpoint")

        if not passes_ruthless_scrubbing(item):
            continue

        doc_id = f"doc_{current_idx}"
        if not is_unique(item["code"], doc_id):
            continue

        cleaned_buffer.append(item)

        # Stage batch locally as a Parquet file without committing to HF immediately
        if len(cleaned_buffer) >= BATCH_SIZE:
            shard_counter += 1
            shard_path = f"{STAGING_DIR}/shard_{int(now)}_{shard_counter}.parquet"
            shard = Dataset.from_list(cleaned_buffer)
            shard.to_parquet(shard_path)
            print(f"Staged local shard: {shard_path} | Scanned: {current_idx}")

            cleaned_buffer = []
            state["current_url"] = target_url
            state["last_index"] = current_idx

    state["completed_urls"].append(target_url)
    state["current_url"] = None
    state["last_index"] = 0

# Final flush upon script completion
if cleaned_buffer:
    shard_counter += 1
    shard = Dataset.from_list(cleaned_buffer)
    shard.to_parquet(f"{STAGING_DIR}/shard_{int(time.time())}_{shard_counter}.parquet")

sync_staging_to_hf(state, commit_msg="Pipeline complete: Final dataset shards uploaded")
print(f"\nExecution complete! Gold Dataset ready at https://huggingface.co/datasets/{REPO_ID}")
